(() => {
  'use strict';

  const GAME='opoong-pizza', BEST_KEY='opoong_pizza_best_v1', PANEL_ID='gameOpoongPizzaPanel';
  const TOPPINGS=[
    {id:'pepperoni',label:'페퍼로니',icon:'🔴'},{id:'mushroom',label:'버섯',icon:'🍄'},{id:'olive',label:'올리브',icon:'🫒'},
    {id:'corn',label:'옥수수',icon:'🌽'},{id:'shrimp',label:'새우',icon:'🍤'},{id:'pineapple',label:'파인애플',icon:'🍍'}
  ];
  const POS=[[34,35],[52,29],[68,40],[39,53],[58,51],[70,61],[31,68],[50,70],[64,75],[44,43],[60,37],[47,59]];
  let state=null,raf=0,last=0,nextOrderTimer=0;
  const q=id=>document.getElementById(id);
  const best=()=>Math.max(0,Number(localStorage.getItem(BEST_KEY)||0)||0);
  const saveBest=v=>{const b=Math.max(best(),Math.floor(v||0));try{localStorage.setItem(BEST_KEY,String(b));}catch(_){}return b;};
  const shuffle=a=>{const c=a.slice();for(let i=c.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[c[i],c[j]]=[c[j],c[i]];}return c;};

  function styles(){if(q('opoongPizzaStyles'))return;const s=document.createElement('style');s.id='opoongPizzaStyles';s.textContent=`
    .coverPizza{position:relative;overflow:hidden;display:grid;place-items:center;background:linear-gradient(145deg,#fff7ed,#fed7aa)}.coverPizza:before{content:'🍕';font-size:58px;filter:drop-shadow(0 9px 12px rgba(194,65,12,.18))}.coverPizza:after{content:'O.P';position:absolute;right:10%;top:10%;padding:5px 8px;border-radius:9px;background:#dc2626;color:#fff;font-size:10px;font-weight:1000;transform:rotate(7deg)}
    .pizzaHud{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin-bottom:11px}.pizzaStat{padding:11px 8px;border:1px solid var(--line);border-radius:17px;background:var(--card);text-align:center}.pizzaStat span{display:block;color:var(--muted);font-size:10.5px;font-weight:900}.pizzaStat strong{display:block;margin-top:4px;font-size:19px;font-weight:1000}
    .pizzaWrap{border:1px solid var(--line);border-radius:26px;background:color-mix(in srgb,var(--card) 94%,var(--bg));padding:14px;display:grid;grid-template-columns:minmax(0,1.05fr) minmax(260px,.95fr);gap:12px}.pizzaKitchen{position:relative;min-height:440px;border-radius:24px;overflow:hidden;background:linear-gradient(180deg,#fff7ed 0 34%,#fed7aa 34% 62%,#fdba74 62%);border:1px solid #fed7aa;padding:14px}.pizzaSign{display:flex;justify-content:space-between;gap:10px;align-items:center;padding:10px 13px;border-radius:17px;background:#fff;border:1px solid #fed7aa;color:#9a3412}.pizzaSign b{font-size:17px}.pizzaSign span{font-size:10.5px;font-weight:900}
    .pizzaOrder{margin-top:10px;padding:12px;border-radius:18px;background:rgba(255,255,255,.9);border:1px solid #fed7aa}.pizzaOrder small{color:#9a3412;font-weight:950}.pizzaOrderList{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px}.pizzaOrderChip{padding:6px 9px;border-radius:999px;background:#fff7ed;border:1px solid #fdba74;font-size:11px;font-weight:900;color:#7c2d12}
    .pizzaBoard{position:relative;width:min(300px,78vw);aspect-ratio:1;margin:18px auto 0;border-radius:50%;background:#d97706;box-shadow:0 18px 32px rgba(124,45,18,.18);display:grid;place-items:center}.pizzaDough{position:absolute;inset:8%;border-radius:50%;background:#fde68a;border:10px solid #f59e0b;box-shadow:inset 0 0 0 5px #ef4444}.pizzaCheese{position:absolute;inset:19%;border-radius:50%;background:#facc15;opacity:.9}.pizzaToppingIcon{position:absolute;transform:translate(-50%,-50%);font-size:26px;filter:drop-shadow(0 3px 2px rgba(124,45,18,.15))}
    .pizzaSide{display:flex;flex-direction:column;gap:10px}.pizzaTools{display:grid;grid-template-columns:1fr 1fr;gap:8px}.pizzaTool{min-height:68px;padding:8px;border:1px solid var(--line);border-radius:17px;background:var(--card);color:var(--text);font-weight:950}.pizzaTool span{display:block;font-size:24px}.pizzaTool.active{border-color:#f97316;background:#fff7ed;box-shadow:0 0 0 3px rgba(249,115,22,.1)}
    .pizzaOven{padding:12px;border:1px solid var(--line);border-radius:18px;background:var(--card)}.pizzaOvenHead{display:flex;justify-content:space-between;gap:8px;font-size:11px;font-weight:900;color:var(--muted)}.pizzaBakeTrack{position:relative;height:22px;margin-top:9px;border-radius:999px;background:#e2e8f0;overflow:hidden}.pizzaBakeIdeal{position:absolute;left:62%;width:20%;top:0;bottom:0;background:#86efac}.pizzaBakeFill{position:absolute;left:0;top:0;bottom:0;width:0;background:linear-gradient(90deg,#fde047,#f97316,#dc2626)}.pizzaBakeMarker{position:absolute;top:-2px;bottom:-2px;width:4px;background:#0f172a;left:0;box-shadow:0 0 0 2px rgba(255,255,255,.45)}
    .pizzaActions{display:grid;grid-template-columns:1fr 1fr;gap:8px}.pizzaActions button{min-height:48px;border-radius:16px;font-weight:1000}.pizzaBakeBtn{border:0;background:linear-gradient(135deg,#ea580c,#dc2626);color:#fff}.pizzaClearBtn{border:1px solid var(--line);background:var(--card);color:var(--text)}.pizzaMessage{min-height:42px;padding:11px;border:1px solid var(--line);border-radius:16px;background:var(--card);color:var(--muted);font-size:11.5px;font-weight:900;line-height:1.5;text-align:center}
    .pizzaOverlay{position:absolute;inset:0;z-index:7;display:grid;place-items:center;padding:20px;background:rgba(124,45,18,.35);backdrop-filter:blur(5px)}.pizzaOverlay[hidden]{display:none!important}.pizzaOverlayCard{max-width:470px;padding:22px;border-radius:24px;background:var(--card);border:1px solid var(--line);text-align:center;box-shadow:0 24px 70px rgba(124,45,18,.2)}.pizzaOverlayCard b{display:block;font-size:27px}.pizzaOverlayCard p{margin:9px 0 16px;color:var(--muted);font-size:13px;font-weight:800;line-height:1.7}
    @media(max-width:760px){.pizzaHud{grid-template-columns:1fr 1fr}.pizzaWrap{grid-template-columns:1fr}.pizzaKitchen{min-height:400px}.pizzaTools{grid-template-columns:repeat(3,1fr)}}@media(max-width:500px){.pizzaTools{grid-template-columns:1fr 1fr}}
  `;document.head.appendChild(s);}

  function html(){return `<div class="pizzaHud"><div class="pizzaStat"><span>남은 시간</span><strong id="pizzaTime">75초</strong></div><div class="pizzaStat"><span>매출</span><strong id="pizzaRevenue">0원</strong></div><div class="pizzaStat"><span>완성</span><strong id="pizzaServed">0판</strong></div><div class="pizzaStat"><span>콤보</span><strong id="pizzaCombo">0</strong></div></div><div class="pizzaWrap"><div class="pizzaKitchen"><div class="pizzaSign"><b>🍕 O.Poong Pizza</b><span>주문 → 토핑 → 굽기 → 꺼내기</span></div><div class="pizzaOrder"><small>현재 주문</small><div class="pizzaOrderList" id="pizzaOrderList"></div></div><div class="pizzaBoard"><div class="pizzaDough"></div><div class="pizzaCheese"></div><div id="pizzaToppingStage"></div></div><div class="pizzaOverlay" id="pizzaOverlay"><div class="pizzaOverlayCard"><b>O.Poong Pizza 🍕</b><p>주문표와 같은 토핑을 올린 뒤 오븐에 넣으세요.<br>굽기 게이지가 <b>초록 구간</b>에 들어왔을 때 꺼내면 완벽한 피자!</p><button class="bigBtn" id="pizzaStart" type="button">영업 시작</button></div></div></div><div class="pizzaSide"><div class="pizzaTools" id="pizzaTools"></div><div class="pizzaOven"><div class="pizzaOvenHead"><span>오븐 굽기</span><b id="pizzaBakeText">준비</b></div><div class="pizzaBakeTrack"><i class="pizzaBakeIdeal"></i><i class="pizzaBakeFill" id="pizzaBakeFill"></i><i class="pizzaBakeMarker" id="pizzaBakeMarker"></i></div></div><div class="pizzaActions"><button class="pizzaClearBtn" id="pizzaClear" type="button">토핑 초기화</button><button class="pizzaBakeBtn" id="pizzaBake" type="button">오븐에 넣기</button></div><div class="pizzaMessage" id="pizzaMessage">주문에 맞는 토핑을 골라주세요.</div></div></div>`;}

  function fresh(){return{running:false,time:75,revenue:0,served:0,combo:0,selected:new Set(),order:[],baking:false,bake:0};}
  function order(){if(!state)return;state.order=shuffle(TOPPINGS).slice(0,2+Math.floor(Math.random()*3)).map(t=>t.id);state.selected=new Set();state.baking=false;state.bake=0;render();}
  function renderTools(){const el=q('pizzaTools');if(!el||!state)return;el.innerHTML=TOPPINGS.map(t=>`<button class="pizzaTool${state.selected.has(t.id)?' active':''}" type="button" data-topping="${t.id}"><span>${t.icon}</span>${t.label}</button>`).join('');el.querySelectorAll('[data-topping]').forEach(b=>b.addEventListener('click',()=>toggle(b.dataset.topping)));}
  function renderPie(){const el=q('pizzaToppingStage');if(!el||!state)return;let n=0,out='';for(const id of state.selected){const t=TOPPINGS.find(x=>x.id===id);if(!t)continue;for(let i=0;i<2;i++){const [x,y]=POS[n++%POS.length];out+=`<span class="pizzaToppingIcon" style="left:${x}%;top:${y}%">${t.icon}</span>`;}}el.innerHTML=out;}
  function renderBake(){if(!state)return;const pct=Math.min(100,state.bake);q('pizzaBakeFill')&&(q('pizzaBakeFill').style.width=`${pct}%`);q('pizzaBakeMarker')&&(q('pizzaBakeMarker').style.left=`${Math.min(99,pct)}%`);q('pizzaBakeText')&&(q('pizzaBakeText').textContent=state.baking?`${Math.round(pct)}%`:pct?`${Math.round(pct)}%`:'준비');q('pizzaBake')&&(q('pizzaBake').textContent=state.baking?'지금 꺼내기!':'오븐에 넣기');}
  function render(){if(!state)return;q('pizzaTime')&&(q('pizzaTime').textContent=`${Math.max(0,Math.ceil(state.time))}초`);q('pizzaRevenue')&&(q('pizzaRevenue').textContent=`${Math.floor(state.revenue).toLocaleString()}원`);q('pizzaServed')&&(q('pizzaServed').textContent=`${state.served}판`);q('pizzaCombo')&&(q('pizzaCombo').textContent=String(state.combo));const list=q('pizzaOrderList');if(list)list.innerHTML=state.order.map(id=>{const t=TOPPINGS.find(x=>x.id===id);return `<span class="pizzaOrderChip">${t?.icon||''} ${t?.label||id}</span>`;}).join('');renderTools();renderPie();renderBake();}
  function toggle(id){if(!state?.running||state.baking)return;state.selected.has(id)?state.selected.delete(id):state.selected.add(id);renderTools();renderPie();}
  function clear(){if(!state?.running||state.baking)return;state.selected.clear();renderTools();renderPie();q('pizzaMessage')&&(q('pizzaMessage').textContent='토핑을 모두 뺐어요.');}
  function exact(){return[...state.selected].sort().join('|')===state.order.slice().sort().join('|');}
  function action(){if(!state?.running)return;if(!state.baking){if(!state.selected.size){q('pizzaMessage')&&(q('pizzaMessage').textContent='토핑을 먼저 올려주세요.');return;}state.baking=true;state.bake=0;q('pizzaMessage')&&(q('pizzaMessage').textContent='오븐 가동! 초록 구간에서 꺼내세요.');return;}serve(false);}
  function serve(burnt){if(!state?.running||!state.baking)return;state.baking=false;const ok=exact(),ideal=state.bake>=62&&state.bake<=82&&!burnt;let earned=0;if(ok&&ideal){state.combo++;state.served++;earned=900+state.combo*120+state.order.length*90;state.revenue+=earned;q('pizzaMessage')&&(q('pizzaMessage').textContent=`완벽! +${earned.toLocaleString()}원 · ${state.combo} 콤보`);}else if(ok&&!burnt&&state.bake>=48&&state.bake<95){state.combo=0;state.served++;earned=420+state.order.length*60;state.revenue+=earned;q('pizzaMessage')&&(q('pizzaMessage').textContent=`조금 아쉽지만 판매 성공! +${earned.toLocaleString()}원`);}else{state.combo=0;q('pizzaMessage')&&(q('pizzaMessage').textContent=burnt?'피자가 타버렸어요! 다음 주문으로 넘어갑니다.':'주문 토핑이 다르거나 굽기 타이밍을 놓쳤어요.');}render();clearTimeout(nextOrderTimer);nextOrderTimer=setTimeout(()=>state?.running&&order(),650);}
  function loop(now){if(!state?.running)return;if(!last)last=now;const dt=Math.min(.06,Math.max(0,(now-last)/1000));last=now;state.time=Math.max(0,state.time-dt);if(state.baking){state.bake+=31*dt;if(state.bake>=100){state.bake=100;serve(true);}}renderBake();q('pizzaTime')&&(q('pizzaTime').textContent=`${Math.max(0,Math.ceil(state.time))}초`);if(state.time<=0)return end();raf=requestAnimationFrame(loop);}
  function start(){cancelAnimationFrame(raf);clearTimeout(nextOrderTimer);raf=0;last=0;state=fresh();state.running=true;order();q('pizzaOverlay')&&(q('pizzaOverlay').hidden=true);q('pizzaMessage')&&(q('pizzaMessage').textContent='주문표와 같은 토핑을 올려주세요.');raf=requestAnimationFrame(loop);}
  function end(){if(!state?.running)return;state.running=false;cancelAnimationFrame(raf);raf=0;clearTimeout(nextOrderTimer);const revenue=Math.floor(state.revenue),b=saveBest(revenue);const meta=q('gameCardOpoongPizza')?.querySelector('.gameCardInfo span');if(meta)meta.textContent=`최고 매출 ${b.toLocaleString()}원`;window.OpoongGameResults?.show(GAME,{title:'O.Poong Pizza',primaryLabel:'최종 매출',primaryValue:`${revenue.toLocaleString()}원`,stats:[{label:'완성',value:`${state.served}판`},{label:'최고 매출',value:`${b.toLocaleString()}원`}]})||window.showGameOverAd?.(GAME);}
  function open(){stop();state=fresh();order();const o=q('pizzaOverlay');if(o)o.hidden=false;q('pizzaMessage')&&(q('pizzaMessage').textContent='주문에 맞는 토핑을 골라주세요.');q(PANEL_ID)?.scrollIntoView({behavior:'smooth',block:'start'});}
  function stop(){cancelAnimationFrame(raf);raf=0;last=0;clearTimeout(nextOrderTimer);if(state)state.running=false;}
  function mount(core){styles();core.addCard({id:'gameCardOpoongPizza',title:'O.Poong Pizza',coverClass:'coverPizza',meta:`최고 매출 ${best().toLocaleString()}원`,game:GAME});core.addPanel(PANEL_ID,html());q('pizzaStart')?.addEventListener('click',start);q('pizzaClear')?.addEventListener('click',clear);q('pizzaBake')?.addEventListener('click',action);}
  function install(){const core=window.OpoongFreshGames;if(!core?.register){setTimeout(install,100);return;}core.register(GAME,{panelId:PANEL_ID,mount,open,stop});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
