(()=>{'use strict';
const G='racing',K='opoong_racing_best_v1',q=id=>document.getElementById(id),best=()=>Math.max(0,Math.floor(+localStorage.getItem(K)||0));let baseOpen,baseHub,baseStop,s=null,raf=0,installed=false;
function style(){if(q('racingGameStyle'))return;const x=document.createElement('style');x.id='racingGameStyle';x.textContent=`.coverRacing{display:grid;place-items:center;background:linear-gradient(90deg,#22c55e 0 16%,#334155 16% 84%,#22c55e 84%)}.coverRacing:before{content:'🏎️';font-size:48px;filter:drop-shadow(0 8px 10px #0003)}.rcHud{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:12px}.rcHud div{padding:11px;border:1px solid var(--line);border-radius:16px;background:var(--card);text-align:center}.rcHud span{display:block;color:var(--muted);font-size:10px;font-weight:900}.rcHud strong{display:block;margin-top:4px;font-size:18px}.rcWrap{display:grid;place-items:center;padding:8px;border:1px solid var(--line);border-radius:24px;background:var(--card2)}#racingCanvas{width:min(100%,520px);height:auto;border-radius:18px;touch-action:none}.rcBtns{display:flex;gap:8px;justify-content:center;flex-wrap:wrap;margin-top:12px}.rcHint{text-align:center;margin-top:9px;color:var(--muted);font-size:12px;font-weight:850}@media(max-width:620px){.rcHud{grid-template-columns:1fr 1fr}.rcHud div:last-child{grid-column:1/-1}}`;document.head.appendChild(x)}
function card(){const g=document.querySelector('#gameHub .gameCardGrid');if(!g||q('gameCardRacing'))return;const b=document.createElement('button');b.className='gameCard';b.type='button';b.id='gameCardRacing';b.innerHTML=`<span class="gameCover coverRacing"></span><span class="gameCardInfo"><b>미니 레이싱</b><span id="gameCardRacingMeta">최고 ${best()}m</span></span>`;b.onclick=()=>window.openMiniGame(G);g.appendChild(b)}
function panel(){const v=q('view-game'),shop=q('gameColorShop');if(!v||q('gameRacingPanel'))return;const p=document.createElement('div');p.id='gameRacingPanel';p.className='gamePlayCard miniGamePanel';p.hidden=true;p.innerHTML=`<div class="rcHud"><div><span>주행 거리</span><strong id="racingDistance">0m</strong></div><div><span>최고 기록</span><strong id="racingBest">${best()}m</strong></div><div><span>속도</span><strong id="racingSpeed">1.0×</strong></div></div><div class="rcWrap"><canvas id="racingCanvas" width="420" height="620"></canvas></div><div class="rcBtns"><button id="racingLeft" class="btn ghost">← 왼쪽</button><button id="racingStart" class="bigBtn">레이스 시작</button><button id="racingRight" class="btn ghost">오른쪽 →</button></div><div class="rcHint">화면 왼쪽·오른쪽을 터치하거나 방향 버튼으로 차선을 바꾸세요. 시간이 지날수록 빨라집니다.</div>`;shop?.parentNode?shop.parentNode.insertBefore(p,shop):v.appendChild(p)}
function reset(){cancelAnimationFrame(raf);s={run:false,end:false,lane:1,dist:0,speed:220,last:0,spawn:.7,stripe:0,obs:[]};q('racingDistance').textContent='0m';q('racingBest').textContent=`${best()}m`;q('racingSpeed').textContent='1.0×';q('racingStart').textContent='레이스 시작';draw()}
const lx=l=>96+l*114;function move(d){if(!s)return;s.lane=Math.max(0,Math.min(2,s.lane+d));draw()}function spawn(){s.obs.push({lane:Math.floor(Math.random()*3),y:-90,h:72,w:48,k:Math.random()<.5})}
function draw(){const c=q('racingCanvas');if(!c||!s)return;const x=c.getContext('2d'),w=c.width,h=c.height;x.fillStyle='#16a34a';x.fillRect(0,0,w,h);x.fillStyle='#334155';x.fillRect(42,0,w-84,h);x.fillStyle='#64748b';x.fillRect(48,0,5,h);x.fillRect(w-53,0,5,h);x.strokeStyle='#fffC';x.lineWidth=4;x.setLineDash([24,22]);x.lineDashOffset=s.stripe;[153,267].forEach(v=>{x.beginPath();x.moveTo(v,0);x.lineTo(v,h);x.stroke()});x.setLineDash([]);s.obs.forEach(o=>{const X=lx(o.lane);x.fillStyle=o.k?'#f59e0b':'#ef4444';x.beginPath();x.roundRect(X-o.w/2,o.y,o.w,o.h,10);x.fill();x.fillStyle='#dbeafe';x.fillRect(X-16,o.y+9,32,13);x.fillStyle='#0f172a';x.fillRect(X-19,o.y+46,38,11)});const X=lx(s.lane),Y=h-102;x.fillStyle='#2563eb';x.beginPath();x.roundRect(X-25,Y,50,76,12);x.fill();x.fillStyle='#bfdbfe';x.fillRect(X-16,Y+11,32,18);x.fillStyle='#0f172a';x.fillRect(X-19,Y+50,38,12);x.fillStyle='#fff';x.font='900 11px system-ui';x.textAlign='center';x.fillText('O.P',X,Y+45)}
function finish(){if(!s||s.end)return;s.run=false;s.end=true;cancelAnimationFrame(raf);const d=Math.floor(s.dist),b=Math.max(best(),d);localStorage.setItem(K,b);q('racingBest').textContent=`${b}m`;q('racingStart').textContent='다시 시작';const m=q('gameCardRacingMeta');if(m)m.textContent=`최고 ${b}m`;if(window.OpoongGameResults?.show)window.OpoongGameResults.show(G,{title:'미니 레이싱',primaryLabel:'주행 거리',primaryValue:`${d}m`,stats:[{label:'최고 기록',value:`${b}m`},{label:'최종 속도',value:`${(s.speed/220).toFixed(1)}×`}]});else window.showGameOverAd?.(G)}
function loop(n){if(!s?.run)return;const dt=Math.min(.04,Math.max(0,(n-s.last)/1000));s.last=n;s.speed=Math.min(520,s.speed+8*dt);s.dist+=s.speed*dt*.12;s.spawn-=dt;s.stripe+=s.speed*dt*.5;if(s.spawn<=0){spawn();s.spawn=Math.max(.38,.95-(s.speed-220)/700)+Math.random()*.22}s.obs.forEach(o=>o.y+=s.speed*dt);s.obs=s.obs.filter(o=>o.y<700);if(s.obs.some(o=>o.lane===s.lane&&o.y+o.h>524&&o.y<588)){draw();return finish()}q('racingDistance').textContent=`${Math.floor(s.dist)}m`;q('racingSpeed').textContent=`${(s.speed/220).toFixed(1)}×`;draw();raf=requestAnimationFrame(loop)}
function start(){reset();s.run=true;s.last=performance.now();q('racingStart').textContent='다시 시작';raf=requestAnimationFrame(loop)}function stop(){cancelAnimationFrame(raf);raf=0;if(s)s.run=false}
function open(){stop();document.querySelectorAll('#view-game .miniGamePanel').forEach(e=>e.hidden=true);q('gameHub').hidden=true;q('miniGameTopbar').hidden=false;q('miniGameTitle').textContent='미니 레이싱';q('gameRacingPanel').hidden=false;reset()}
function bind(){q('racingStart').onclick=start;q('racingLeft').onclick=()=>move(-1);q('racingRight').onclick=()=>move(1);q('racingCanvas').onpointerdown=e=>{const r=e.currentTarget.getBoundingClientRect();move(e.clientX<r.left+r.width/2?-1:1)};window.addEventListener('keydown',e=>{if(q('gameRacingPanel')&&!q('gameRacingPanel').hidden&&(e.key==='ArrowLeft'||e.key==='ArrowRight')){e.preventDefault();move(e.key==='ArrowLeft'?-1:1)}})}
function wrap(){baseOpen=window.openMiniGame;baseHub=window.showMiniGameHub;baseStop=window.stopActiveMiniGame;if(typeof baseOpen!=='function')return false;window.openMiniGame=function(g){if(g===G)return open();stop();return baseOpen.apply(this,arguments)};if(typeof baseHub==='function')window.showMiniGameHub=function(){stop();const r=baseHub.apply(this,arguments);q('gameRacingPanel').hidden=true;return r};if(typeof baseStop==='function')window.stopActiveMiniGame=function(){stop();return baseStop.apply(this,arguments)};return true}
function install(){if(installed)return;if(typeof window.openMiniGame!=='function'||!document.querySelector('#gameHub .gameCardGrid'))return setTimeout(install,160);installed=true;style();card();panel();bind();wrap();reset()}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',install,{once:true}):install();})();
