(() => {
  'use strict';

  const GAME='opoong-pungtal', BEST_KEY='opoong_pungtal_best_v1', PANEL_ID='gameOpoongPungtalPanel';
  let state=null,tick=0,memoryTimer=0;
  const q=id=>document.getElementById(id);
  const best=()=>Math.max(0,Number(localStorage.getItem(BEST_KEY)||0)||0);
  const saveBest=v=>{const n=Math.max(1,Math.floor(v||0)),old=best(),b=!old||n<old?n:old;try{localStorage.setItem(BEST_KEY,String(b));}catch(_){}return b;};
  const shuffle=a=>{const c=a.slice();for(let i=c.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[c[i],c[j]]=[c[j],c[i]];}return c;};

  function styles(){if(q('opoongPungtalStyles'))return;const s=document.createElement('style');s.id='opoongPungtalStyles';s.textContent=`
    .coverPungtal{position:relative;overflow:hidden;display:grid;place-items:center;background:linear-gradient(145deg,#0f172a,#1e3a5f)}.coverPungtal:before{content:'탈';width:62px;height:62px;display:grid;place-items:center;border-radius:20px;background:#fff;color:#0f172a;font-size:35px;font-weight:1000;box-shadow:0 14px 30px rgba(0,0,0,.25)}.coverPungtal:after{content:'EXIT';position:absolute;right:12%;bottom:12%;color:#86efac;font-size:11px;font-weight:1000;letter-spacing:1.5px}
    .pungtalHud{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin-bottom:11px}.pungtalStat{padding:11px 8px;border:1px solid var(--line);border-radius:17px;background:var(--card);text-align:center}.pungtalStat span{display:block;color:var(--muted);font-size:10.5px;font-weight:900}.pungtalStat strong{display:block;margin-top:4px;font-size:19px;font-weight:1000}
    .pungtalWrap{border:1px solid var(--line);border-radius:26px;background:color-mix(in srgb,var(--card) 94%,var(--bg));padding:14px}.pungtalScene{position:relative;min-height:470px;border-radius:24px;overflow:hidden;border:1px solid var(--line);background:linear-gradient(180deg,#e0f2fe 0 34%,#f8fafc 34% 72%,#cbd5e1 72%);padding:16px;display:grid;place-items:center}.pungtalScene:before{content:'';position:absolute;left:7%;right:7%;top:12%;height:150px;border-radius:22px;background:linear-gradient(180deg,#fff,#f8fafc);border:8px solid #64748b;box-shadow:0 18px 0 #475569}
    .pungtalPuzzle{position:relative;z-index:2;width:min(620px,94%);padding:20px;border-radius:24px;background:rgba(255,255,255,.95);border:1px solid var(--line);box-shadow:0 24px 60px rgba(15,23,42,.15);text-align:center}.pungtalPuzzle .room{display:inline-flex;padding:6px 10px;border-radius:999px;background:#eff6ff;color:#1d4ed8;font-size:10.5px;font-weight:1000}.pungtalPuzzle h3{margin:10px 0 4px;font-size:24px}.pungtalPuzzle p{margin:0;color:var(--muted);font-size:12.5px;font-weight:850;line-height:1.65}
    .pungtalChoices{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:14px}.pungtalChoice{min-height:48px;border:1px solid var(--line);border-radius:16px;background:var(--card2);color:var(--text);font-weight:1000}.pungtalChoice:hover{border-color:var(--pri)}.pungtalArrows{display:flex;justify-content:center;gap:8px;flex-wrap:wrap;margin-top:15px}.pungtalArrow{width:58px;height:54px;border:1px solid var(--line);border-radius:16px;background:var(--card2);font-size:22px;font-weight:1000}.pungtalMemory{margin-top:14px;padding:13px;border-radius:17px;background:#0f172a;color:#fff;font-size:28px;font-weight:1000;letter-spacing:8px;min-height:58px;display:grid;place-items:center}
    .pungtalBooks{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:15px}.pungtalBook{min-height:90px;border:0;border-radius:12px 20px 20px 12px;background:linear-gradient(90deg,#1d4ed8,#60a5fa);color:#fff;font-size:24px;font-weight:1000;box-shadow:inset 8px 0 rgba(255,255,255,.16),0 10px 20px rgba(37,99,235,.15)}.pungtalBook.done{opacity:.35;transform:translateY(4px)}.pungtalCode{width:min(280px,90%);margin:14px auto 0;display:block;padding:14px 16px;border:2px solid var(--line);border-radius:17px;background:var(--card);color:var(--text);font-size:25px;font-weight:1000;text-align:center;letter-spacing:9px;outline:0}.pungtalCode:focus{border-color:var(--pri)}
    .pungtalKeys{display:flex;justify-content:center;gap:8px;margin-top:9px}.pungtalKey{min-width:44px;padding:8px 10px;border-radius:12px;background:#0f172a;color:#fff;font-size:18px;font-weight:1000}.pungtalProgress{display:flex;gap:5px;margin-top:10px}.pungtalProgress i{height:7px;flex:1;border-radius:999px;background:var(--line)}.pungtalProgress i.done{background:var(--ok)}.pungtalMessage{min-height:22px;margin-top:10px;color:var(--muted);font-size:12px;font-weight:900;text-align:center}
    .pungtalOverlay{position:absolute;inset:0;z-index:7;display:grid;place-items:center;padding:20px;background:rgba(15,23,42,.5);backdrop-filter:blur(5px)}.pungtalOverlay[hidden]{display:none!important}.pungtalOverlayCard{max-width:470px;padding:22px;border-radius:24px;background:var(--card);border:1px solid var(--line);text-align:center;box-shadow:0 24px 70px rgba(15,23,42,.2)}.pungtalOverlayCard b{display:block;font-size:27px}.pungtalOverlayCard p{margin:9px 0 16px;color:var(--muted);font-size:13px;font-weight:800;line-height:1.7}
    @media(max-width:620px){.pungtalHud{grid-template-columns:1fr 1fr}.pungtalScene{min-height:440px}.pungtalChoices{grid-template-columns:1fr}.pungtalBooks{grid-template-columns:1fr 1fr}}
  `;document.head.appendChild(s);}

  function html(){const b=best();return `<div class="pungtalHud"><div class="pungtalStat"><span>남은 시간</span><strong id="pungtalTime">180초</strong></div><div class="pungtalStat"><span>진행</span><strong id="pungtalStage">0 / 4</strong></div><div class="pungtalStat"><span>실수</span><strong id="pungtalMistakes">0회</strong></div><div class="pungtalStat"><span>최고 기록</span><strong id="pungtalBest">${b?b+'초':'-'}</strong></div></div><div class="pungtalWrap"><div class="pungtalScene"><div class="pungtalPuzzle" id="pungtalPuzzle"></div><div class="pungtalOverlay" id="pungtalOverlay"><div class="pungtalOverlayCard"><b>풍탈 · 풍산탈출 🚪</b><p>교실에서 시작해 복도와 도서관의 퍼즐을 풀고 정문까지 탈출하세요.<br>실제 학교 비밀번호와는 전혀 관계없는 랜덤 퍼즐이에요.</p><button class="bigBtn" id="pungtalStart" type="button">탈출 시작</button></div></div></div><div class="pungtalProgress" id="pungtalProgress"><i></i><i></i><i></i><i></i></div><div class="pungtalMessage" id="pungtalMessage">4개의 퍼즐을 통과하면 탈출 성공!</div></div>`;}

  function fresh(){return{running:false,time:180,startedAt:0,stage:0,mistakes:0,keys:[],arrows:[],arrowInput:[],bookNext:1};}
  function clearTimers(){clearInterval(tick);tick=0;clearTimeout(memoryTimer);memoryTimer=0;}
  function hud(){if(!state)return;q('pungtalTime')&&(q('pungtalTime').textContent=`${Math.max(0,Math.ceil(state.time))}초`);q('pungtalStage')&&(q('pungtalStage').textContent=`${Math.min(4,state.stage)} / 4`);q('pungtalMistakes')&&(q('pungtalMistakes').textContent=`${state.mistakes}회`);q('pungtalBest')&&(q('pungtalBest').textContent=best()?`${best()}초`:'-');document.querySelectorAll('#pungtalProgress i').forEach((el,i)=>el.classList.toggle('done',i<state.stage));}
  function keyHtml(){return `<div class="pungtalKeys">${[0,1,2].map(i=>`<span class="pungtalKey">${state.keys[i]??'?'}</span>`).join('')}</div>`;}
  function giveKey(){const d=Math.floor(Math.random()*10);state.keys.push(d);return d;}
  function wrong(msg){state.mistakes++;state.time=Math.max(0,state.time-3);hud();q('pungtalMessage')&&(q('pungtalMessage').textContent=`${msg} · 3초 페널티`);}
  function next(){state.stage++;hud();if(state.stage>=4)return success();setTimeout(renderStage,520);}

  function renderStage(){if(!state?.running)return;const box=q('pungtalPuzzle');if(!box)return;
    if(state.stage===0){const a=2+Math.floor(Math.random()*5),b=2+Math.floor(Math.random()*5),c=1+Math.floor(Math.random()*4),answer=a*b+c;const options=shuffle([answer,answer+2,Math.max(1,answer-3),answer+5]);box.innerHTML=`<span class="room">1 · 교실</span><h3>칠판의 첫 암호</h3><p>${a} × ${b} + ${c} = ?<br>정답을 고르면 교실 문이 열려요.</p><div class="pungtalChoices">${options.map(v=>`<button class="pungtalChoice" data-math="${v}">${v}</button>`).join('')}</div>${keyHtml()}`;box.querySelectorAll('[data-math]').forEach(btn=>btn.addEventListener('click',()=>{if(Number(btn.dataset.math)===answer){const k=giveKey();q('pungtalMessage')&&(q('pungtalMessage').textContent=`교실 탈출! 열쇠 숫자 ${k} 획득`);next();}else wrong('칠판 계산이 틀렸어요');}));return;}
    if(state.stage===1){const dirs=['↑','→','↓','←'];state.arrows=Array.from({length:5},()=>dirs[Math.floor(Math.random()*dirs.length)]);state.arrowInput=[];box.innerHTML=`<span class="room">2 · 복도</span><h3>복도 방향 기억하기</h3><p>잠깐 나타나는 방향을 기억한 뒤 그대로 눌러 CCTV 구간을 통과하세요.</p><div class="pungtalMemory" id="pungtalMemory">${state.arrows.join(' ')}</div><div class="pungtalArrows">${dirs.map(d=>`<button class="pungtalArrow" data-arrow="${d}" disabled>${d}</button>`).join('')}</div>${keyHtml()}`;memoryTimer=setTimeout(()=>{q('pungtalMemory')&&(q('pungtalMemory').textContent='? ? ? ? ?');box.querySelectorAll('[data-arrow]').forEach(b=>b.disabled=false);},1900);box.querySelectorAll('[data-arrow]').forEach(btn=>btn.addEventListener('click',()=>{state.arrowInput.push(btn.dataset.arrow);const i=state.arrowInput.length-1;if(state.arrowInput[i]!==state.arrows[i]){state.arrowInput=[];q('pungtalMemory')&&(q('pungtalMemory').textContent='다시 처음부터');wrong('방향 순서가 달라요');return;}q('pungtalMemory')&&(q('pungtalMemory').textContent=state.arrowInput.join(' '));if(state.arrowInput.length===state.arrows.length){const k=giveKey();q('pungtalMessage')&&(q('pungtalMessage').textContent=`복도 통과! 열쇠 숫자 ${k} 획득`);next();}}));return;}
    if(state.stage===2){state.bookNext=1;const books=shuffle([1,2,3,4]);box.innerHTML=`<span class="room">3 · 도서관</span><h3>책을 순서대로 정리</h3><p>흩어진 책을 <b>1 → 2 → 3 → 4</b> 순서로 눌러 숨겨진 열쇠를 찾으세요.</p><div class="pungtalBooks">${books.map(n=>`<button class="pungtalBook" data-book="${n}">${n}</button>`).join('')}</div>${keyHtml()}`;box.querySelectorAll('[data-book]').forEach(btn=>btn.addEventListener('click',()=>{const n=Number(btn.dataset.book);if(n!==state.bookNext){state.bookNext=1;box.querySelectorAll('[data-book]').forEach(b=>b.classList.remove('done'));wrong('책 순서가 꼬였어요');return;}btn.classList.add('done');state.bookNext++;if(state.bookNext===5){const k=giveKey();q('pungtalMessage')&&(q('pungtalMessage').textContent=`도서관 통과! 열쇠 숫자 ${k} 획득`);next();}}));return;}
    const code=state.keys.join('');box.innerHTML=`<span class="room">4 · 정문</span><h3>마지막 출입문</h3><p>지금까지 모은 세 자리 열쇠 번호를 입력하면 탈출 성공!</p>${keyHtml()}<input id="pungtalCode" class="pungtalCode" inputmode="numeric" maxlength="3" autocomplete="off" placeholder="000"><div class="pungtalChoices"><button class="pungtalChoice" id="pungtalUnlock" type="button">정문 열기</button></div>`;const submit=()=>{const v=String(q('pungtalCode')?.value||'').replace(/\D/g,'').slice(0,3);if(v===code)next();else{q('pungtalCode')&&(q('pungtalCode').value='');wrong('열쇠 번호가 달라요');}};q('pungtalUnlock')?.addEventListener('click',submit);q('pungtalCode')?.addEventListener('keydown',e=>e.key==='Enter'&&submit());q('pungtalCode')?.focus();
  }

  function start(){clearTimers();state=fresh();state.running=true;state.startedAt=performance.now();q('pungtalOverlay')&&(q('pungtalOverlay').hidden=true);q('pungtalMessage')&&(q('pungtalMessage').textContent='교실부터 하나씩 탈출해보세요.');hud();renderStage();tick=setInterval(()=>{if(!state?.running)return;state.time=Math.max(0,state.time-.1);hud();if(state.time<=0)fail();},100);}
  function success(){if(!state?.running)return;state.running=false;clearTimers();const elapsed=Math.max(1,Math.round((performance.now()-state.startedAt)/1000)),b=saveBest(elapsed);state.stage=4;hud();const meta=q('gameCardOpoongPungtal')?.querySelector('.gameCardInfo span');if(meta)meta.textContent=`최고 ${b}초`;q('pungtalPuzzle')&&(q('pungtalPuzzle').innerHTML=`<span class="room">ESCAPED</span><h3>풍탈 성공! 🎉</h3><p>${elapsed}초 만에 정문을 통과했어요.<br>실수 ${state.mistakes}회 · 최고 기록 ${b}초</p>${keyHtml()}`);window.OpoongGameResults?.show(GAME,{title:'풍탈 · 풍산탈출',primaryLabel:'탈출 기록',primaryValue:`${elapsed}초`,stats:[{label:'실수',value:`${state.mistakes}회`},{label:'최고 기록',value:`${b}초`}]})||window.showGameOverAd?.(GAME);}
  function fail(){if(!state?.running)return;state.running=false;clearTimers();q('pungtalPuzzle')&&(q('pungtalPuzzle').innerHTML='<span class="room">TIME OUT</span><h3>정문이 잠겼어요</h3><p>시간 안에 탈출하지 못했어요. 다시 도전해보세요.</p>');window.OpoongGameResults?.show(GAME,{title:'풍탈 · 풍산탈출',primaryLabel:'결과',primaryValue:'탈출 실패',stats:[{label:'통과 구간',value:`${state.stage}/4`},{label:'실수',value:`${state.mistakes}회`}]})||window.showGameOverAd?.(GAME);}
  function open(){stop();state=fresh();hud();q('pungtalPuzzle')&&(q('pungtalPuzzle').innerHTML='<span class="room">READY</span><h3>풍산탈출 준비</h3><p>시작 버튼을 누르면 180초 카운트가 시작돼요.</p>');q('pungtalOverlay')&&(q('pungtalOverlay').hidden=false);q(PANEL_ID)?.scrollIntoView({behavior:'smooth',block:'start'});}
  function stop(){clearTimers();if(state)state.running=false;}
  function mount(core){styles();const b=best();core.addCard({id:'gameCardOpoongPungtal',title:'풍탈 · 풍산탈출',coverClass:'coverPungtal',meta:b?`최고 ${b}초`:'학교 탈출 퍼즐',game:GAME});core.addPanel(PANEL_ID,html());q('pungtalStart')?.addEventListener('click',start);}
  function install(){const core=window.OpoongFreshGames;if(!core?.register){setTimeout(install,100);return;}core.register(GAME,{panelId:PANEL_ID,mount,open,stop});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
