(()=>{'use strict';
const G='pipe',K='opoong_pipe_best_v1',q=id=>document.getElementById(id),D=[[-1,0,1,4],[0,1,2,8],[1,0,4,1],[0,-1,8,2]];let baseOpen,baseHub,baseStop,s=null,timer=0,installed=false;
function style(){if(q('pipeGameStyle'))return;const x=document.createElement('style');x.id='pipeGameStyle';x.textContent=`.coverPipe{display:grid;place-items:center;background:linear-gradient(145deg,#ecfdf5,#d1fae5)}.coverPipe:before{content:'└─┐';font-size:34px;font-weight:1000;color:#059669;letter-spacing:-6px;transform:rotate(-8deg)}.ppHud{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:12px}.ppHud div{padding:11px;border:1px solid var(--line);border-radius:16px;background:var(--card);text-align:center}.ppHud span{display:block;color:var(--muted);font-size:10px;font-weight:900}.ppHud strong{display:block;margin-top:4px;font-size:18px}.ppModes{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:12px}.ppModes button[aria-pressed=true]{color:#fff;background:linear-gradient(135deg,var(--pri),var(--pri2))}.ppBoard{--n:5;display:grid;grid-template-columns:repeat(var(--n),1fr);gap:5px;width:min(100%,560px);margin:auto;padding:10px;border:1px solid var(--line);border-radius:22px;background:color-mix(in srgb,var(--pri) 6%,var(--card))}.ppTile{position:relative;aspect-ratio:1;border:1px solid var(--line);border-radius:12px;background:var(--card);overflow:hidden;padding:0}.ppTile.on{background:color-mix(in srgb,var(--ok) 10%,var(--card))}.ppTile.start{box-shadow:inset 0 0 0 3px color-mix(in srgb,var(--ok) 45%,transparent)}.ppTile.end{box-shadow:inset 0 0 0 3px color-mix(in srgb,var(--pri) 45%,transparent)}.ppArm{position:absolute;left:50%;top:50%;width:16%;height:52%;border-radius:99px;background:#64748b;transform-origin:50% 0;transform:translate(-50%,0) rotate(var(--r))}.ppTile.on .ppArm,.ppTile.on .ppCore{background:var(--ok)}.ppCore{position:absolute;left:50%;top:50%;width:28%;height:28%;border-radius:50%;background:#64748b;transform:translate(-50%,-50%)}.ppBadge{position:absolute;right:4px;bottom:3px;font-size:8px;font-weight:1000;color:var(--muted)}.ppActions{text-align:center;margin-top:12px}.ppStatus{text-align:center;margin-top:9px;color:var(--muted);font-size:12px;font-weight:850}@media(max-width:620px){.ppHud{grid-template-columns:1fr 1fr}.ppHud div:last-child{grid-column:1/-1}.ppBoard{gap:4px;padding:7px}}`;document.head.appendChild(x)}
function load(n){try{return JSON.parse(localStorage.getItem(`${K}_${n}`)||'null')}catch(_){return null}}function save(n,v){localStorage.setItem(`${K}_${n}`,JSON.stringify(v))}
function card(){const g=document.querySelector('#gameHub .gameCardGrid');if(!g||q('gameCardPipe'))return;const b=document.createElement('button');b.className='gameCard';b.type='button';b.id='gameCardPipe';b.innerHTML='<span class="gameCover coverPipe"></span><span class="gameCardInfo"><b>파이프 연결</b><span id="gameCardPipeMeta">회전 퍼즐</span></span>';b.onclick=()=>window.openMiniGame(G);g.appendChild(b);meta()}
function panel(){const v=q('view-game'),shop=q('gameColorShop');if(!v||q('gamePipePanel'))return;const p=document.createElement('div');p.id='gamePipePanel';p.className='gamePlayCard miniGamePanel';p.hidden=true;p.innerHTML=`<div class="ppHud"><div><span>이동 횟수</span><strong id="pipeMoves">0회</strong></div><div><span>시간</span><strong id="pipeTime">0초</strong></div><div><span>최고 기록</span><strong id="pipeBest">-</strong></div></div><div class="ppModes"><button class="smallbtn ghost" data-pipe-size="5" aria-pressed="true">Easy 5×5</button><button class="smallbtn ghost" data-pipe-size="6">Normal 6×6</button><button class="smallbtn ghost" data-pipe-size="7">Hard 7×7</button></div><div id="pipeBoard" class="ppBoard"></div><div class="ppActions"><button id="pipeNew" class="bigBtn">새 퍼즐</button></div><div id="pipeStatus" class="ppStatus">타일을 눌러 90°씩 돌리고 START와 END를 연결하세요.</div>`;shop?.parentNode?shop.parentNode.insertBefore(p,shop):v.appendChild(p)}
function rot(m,n){while(n--)m=((m<<1)&15)|((m>>3)&1);return m}function shuffle(a){a=a.slice();for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function path(n){const st={r:Math.floor(n/2),c:0},en={r:Math.floor(n/2),c:n-1};for(let z=0;z<60;z++){const seen=Array.from({length:n},()=>Array(n).fill(0)),p=[];function dfs(r,c){seen[r][c]=1;p.push({r,c});if(r===en.r&&c===en.c&&p.length>=n+2)return true;const a=shuffle(D).map(d=>({d,nr:r+d[0],nc:c+d[1]})).filter(x=>x.nr>=0&&x.nr<n&&x.nc>=0&&x.nc<n&&!seen[x.nr][x.nc]);for(const x of a)if(dfs(x.nr,x.nc))return true;p.pop();return false}if(dfs(st.r,st.c))return{st,en,p}}return{st,en,p:Array.from({length:n},(_,c)=>({r:st.r,c}))}}
function between(a,b){const r=b.r-a.r,c=b.c-a.c;return r<0?1:c>0?2:r>0?4:8}
function fresh(n=s?.n||5){clearInterval(timer);timer=0;const d=path(n),m=Array.from({length:n},()=>Array(n).fill(0));d.p.forEach((x,i)=>{let k=0;if(i)k|=between(x,d.p[i-1]);if(i<d.p.length-1)k|=between(x,d.p[i+1]);if(!i)k|=8;if(i===d.p.length-1)k|=2;m[x.r][x.c]=k});const set=new Set(d.p.map(x=>`${x.r},${x.c}`)),a=[];for(let r=0;r<n;r++)for(let c=0;c<n;c++){let k=m[r][c];if(!set.has(`${r},${c}`)&&Math.random()<.55)k=[3,5,6,9,10,12,7,11,13,14][Math.floor(Math.random()*10)];a.push({r,c,k,t:Math.floor(Math.random()*4)})}s={n,st:d.st,en:d.en,a,moves:0,sec:0,start:false,done:false};q('pipeBoard').style.setProperty('--n',n);document.querySelectorAll('[data-pipe-size]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.pipeSize===n)));q('pipeStatus').textContent='타일을 눌러 90°씩 돌리고 START와 END를 연결하세요.';render()}
const mask=x=>rot(x.k,x.t);function connected(){const map=new Map(s.a.map(x=>[`${x.r},${x.c}`,x])),st=map.get(`${s.st.r},${s.st.c}`),seen=new Set;if(!st||!(mask(st)&8))return seen;seen.add(`${st.r},${st.c}`);const Q=[st];while(Q.length){const x=Q.shift(),m=mask(x);for(const d of D){if(!(m&d[2]))continue;const r=x.r+d[0],c=x.c+d[1],y=map.get(`${r},${c}`);if(!y||!(mask(y)&d[3]))continue;const k=`${r},${c}`;if(!seen.has(k)){seen.add(k);Q.push(y)}}}return seen}
function solved(seen){const k=`${s.en.r},${s.en.c}`,e=s.a.find(x=>x.r===s.en.r&&x.c===s.en.c);return seen.has(k)&&e&&(mask(e)&2)}
function render(){if(!s)return;const seen=connected();q('pipeBoard').innerHTML=s.a.map((x,i)=>{const m=mask(x),arms=D.filter(d=>m&d[2]).map(d=>`<i class="ppArm" style="--r:${d[2]===1?180:d[2]===2?270:d[2]===4?0:90}deg"></i>`).join(''),st=x.r===s.st.r&&x.c===s.st.c,en=x.r===s.en.r&&x.c===s.en.c;return`<button class="ppTile ${seen.has(`${x.r},${x.c}`)?'on':''} ${st?'start':''} ${en?'end':''}" data-pipe-index="${i}">${arms}<i class="ppCore"></i>${st?'<span class="ppBadge">START</span>':en?'<span class="ppBadge">END</span>':''}</button>`}).join('');q('pipeMoves').textContent=`${s.moves}회`;q('pipeTime').textContent=`${s.sec}초`;const b=load(s.n);q('pipeBest').textContent=b?`${b.moves}회 · ${b.sec}초`:'-';if(solved(seen)&&!s.done)finish()}
function tick(){if(s.start)return;s.start=true;timer=setInterval(()=>{if(!s.done){s.sec++;q('pipeTime').textContent=`${s.sec}초`}},1000)}function turn(i){if(!s||s.done)return;const x=s.a[i];if(!x||!x.k)return;tick();x.t=(x.t+1)%4;s.moves++;render()}
function finish(){if(s.done)return;s.done=true;clearInterval(timer);timer=0;const old=load(s.n),better=!old||s.moves<old.moves||(s.moves===old.moves&&s.sec<old.sec);if(better)save(s.n,{moves:s.moves,sec:s.sec});q('pipeStatus').textContent=better?'완성! 새 최고 기록이에요.':'완성! START와 END가 연결됐어요.';meta();if(window.OpoongGameResults?.show)window.OpoongGameResults.show(G,{title:'파이프 연결',primaryLabel:'이동 횟수',primaryValue:`${s.moves}회`,stats:[{label:'난이도',value:`${s.n}×${s.n}`},{label:'시간',value:`${s.sec}초`} ]});else window.showGameOverAd?.(G)}
function meta(){const e=q('gameCardPipeMeta');if(!e)return;const a=[5,6,7].map(load).filter(Boolean);e.textContent=a.length?`최고 ${Math.min(...a.map(x=>x.moves))}회`:'회전 퍼즐'}function stop(){clearInterval(timer);timer=0}
function open(){stop();document.querySelectorAll('#view-game .miniGamePanel').forEach(e=>e.hidden=true);q('gameHub').hidden=true;q('miniGameTopbar').hidden=false;q('miniGameTitle').textContent='파이프 연결';q('gamePipePanel').hidden=false;fresh(s?.n||5)}
function bind(){q('pipeBoard').onclick=e=>{const b=e.target.closest('[data-pipe-index]');if(b)turn(+b.dataset.pipeIndex)};q('pipeNew').onclick=()=>fresh(s?.n||5);document.querySelectorAll('[data-pipe-size]').forEach(b=>b.onclick=()=>fresh(+b.dataset.pipeSize))}
function wrap(){baseOpen=window.openMiniGame;baseHub=window.showMiniGameHub;baseStop=window.stopActiveMiniGame;if(typeof baseOpen!=='function')return false;window.openMiniGame=function(g){if(g===G)return open();stop();return baseOpen.apply(this,arguments)};if(typeof baseHub==='function')window.showMiniGameHub=function(){stop();const r=baseHub.apply(this,arguments);q('gamePipePanel').hidden=true;return r};if(typeof baseStop==='function')window.stopActiveMiniGame=function(){stop();return baseStop.apply(this,arguments)};return true}
function install(){if(installed)return;if(typeof window.openMiniGame!=='function'||!document.querySelector('#gameHub .gameCardGrid'))return setTimeout(install,140);installed=true;style();card();panel();bind();wrap();fresh(5)}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',install,{once:true}):install();})();
