(()=>{'use strict';
const G='helix',K='opoong_helix_best_v1',q=id=>document.getElementById(id),best=()=>Math.max(0,+localStorage.getItem(K)||0);let baseOpen,baseHub,baseStop,s=null,raf=0,drag=null,installed=false;
function style(){if(q('helixGameStyle'))return;const x=document.createElement('style');x.id='helixGameStyle';x.textContent=`.coverHelix{display:grid;place-items:center;background:linear-gradient(145deg,#dbeafe,#ede9fe);position:relative}.coverHelix:before{content:'';width:58px;height:58px;border-radius:50%;border:12px solid #2563eb;border-right-color:transparent;border-bottom-color:#8b5cf6;transform:rotate(-24deg)}.coverHelix:after{content:'●';position:absolute;color:#f43f5e;font-size:24px;transform:translate(18px,-18px)}.hxHud{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:12px}.hxHud div{padding:11px;border:1px solid var(--line);border-radius:16px;background:var(--card);text-align:center}.hxHud span{display:block;color:var(--muted);font-size:10px;font-weight:900}.hxHud strong{display:block;margin-top:4px;font-size:18px}.hxWrap{display:grid;place-items:center;padding:8px;border:1px solid var(--line);border-radius:24px;background:var(--card2)}#helixCanvas{width:min(100%,520px);height:auto;border-radius:18px;touch-action:none}.hxBtns{display:flex;gap:8px;justify-content:center;flex-wrap:wrap;margin-top:12px}.hxHint{text-align:center;margin-top:9px;color:var(--muted);font-size:12px;font-weight:850}@media(max-width:620px){.hxHud{grid-template-columns:1fr 1fr}.hxHud div:last-child{grid-column:1/-1}}`;document.head.appendChild(x)}
function card(){const g=document.querySelector('#gameHub .gameCardGrid');if(!g||q('gameCardHelix'))return;const b=document.createElement('button');b.className='gameCard';b.type='button';b.id='gameCardHelix';b.innerHTML=`<span class="gameCover coverHelix"></span><span class="gameCardInfo"><b>헬릭스 점프</b><span id="gameCardHelixMeta">최고 ${best()}층</span></span>`;b.onclick=()=>window.openMiniGame(G);g.appendChild(b)}
function panel(){const v=q('view-game'),shop=q('gameColorShop');if(!v||q('gameHelixPanel'))return;const p=document.createElement('div');p.id='gameHelixPanel';p.className='gamePlayCard miniGamePanel';p.hidden=true;p.innerHTML=`<div class="hxHud"><div><span>현재 층</span><strong id="helixScore">0층</strong></div><div><span>최고 기록</span><strong id="helixBest">${best()}층</strong></div><div><span>상태</span><strong id="helixStatus">준비</strong></div></div><div class="hxWrap"><canvas id="helixCanvas" width="420" height="560"></canvas></div><div class="hxBtns"><button id="helixLeft" class="btn ghost" type="button">← 회전</button><button id="helixStart" class="bigBtn" type="button">게임 시작</button><button id="helixRight" class="btn ghost" type="button">회전 →</button></div><div class="hxHint">좌우 드래그로 기둥을 돌려 틈으로 내려가세요. 붉은 구역에 닿으면 종료됩니다.</div>`;shop?.parentNode?shop.parentNode.insertBefore(p,shop):v.appendChild(p)}
function platform(y,i){return{y,i,a:Math.random()*6.28,g:.25+Math.random()*.08,h:Math.random()*6.28,p:false}}
function reset(){cancelAnimationFrame(raf);s={run:false,end:false,rot:0,y:78,vy:0,score:0,last:0,next:9,ps:Array.from({length:9},(_,i)=>platform(155+i*62,i))};q('helixScore').textContent='0층';q('helixBest').textContent=`${best()}층`;q('helixStatus').textContent='준비';q('helixStart').textContent='게임 시작';draw()}
const gx=p=>Math.sin(s.rot+p.a)*.78,hx=p=>Math.sin(s.rot+p.h)*.78;
function draw(){const c=q('helixCanvas');if(!c||!s)return;const x=c.getContext('2d'),w=c.width,h=c.height,m=w/2,gr=x.createLinearGradient(0,0,0,h);gr.addColorStop(0,'#e0f2fe');gr.addColorStop(1,'#ede9fe');x.fillStyle=gr;x.fillRect(0,0,w,h);x.fillStyle='#94a3b8';x.fillRect(m-13,20,26,h);x.fillStyle='#cbd5e1';x.fillRect(m-5,20,10,h);for(const p of s.ps){if(p.y<-30||p.y>h+30)continue;const L=52,R=w-52,gc=m+gx(p)*150,gh=p.g*150;x.fillStyle='#2563eb';x.beginPath();x.roundRect(L,p.y,Math.max(0,gc-gh-L),15,7);x.fill();x.beginPath();x.roundRect(gc+gh,p.y,Math.max(0,R-gc-gh),15,7);x.fill();const hc=m+hx(p)*150,hl=Math.max(L,hc-27),hr=Math.min(R,hc+27);if(hr>hl&&!(hl<gc+gh&&hr>gc-gh)){x.fillStyle='#ef4444';x.beginPath();x.roundRect(hl,p.y,hr-hl,15,7);x.fill()}x.fillStyle='rgba(15,23,42,.5)';x.font='800 10px system-ui';x.fillText(String(p.i+1),24,p.y+11)}x.fillStyle='#f43f5e';x.beginPath();x.arc(m,s.y,12,0,6.28);x.fill();x.fillStyle='#fff9';x.beginPath();x.arc(m-4,s.y-4,4,0,6.28);x.fill()}
function rotate(d){if(!s)return;s.rot+=d;draw()}
function finish(reason){if(!s||s.end)return;s.run=false;s.end=true;cancelAnimationFrame(raf);const b=Math.max(best(),s.score);localStorage.setItem(K,b);q('helixBest').textContent=`${b}층`;q('helixStatus').textContent=reason;q('helixStart').textContent='다시 시작';const m=q('gameCardHelixMeta');if(m)m.textContent=`최고 ${b}층`;if(window.OpoongGameResults?.show)window.OpoongGameResults.show(G,{title:'헬릭스 점프',primaryLabel:'도달 층수',primaryValue:`${s.score}층`,stats:[{label:'최고 기록',value:`${b}층`},{label:'종료',value:reason}]});else window.showGameOverAd?.(G)}
function loop(n){if(!s?.run)return;const dt=Math.min(.035,Math.max(0,(n-s.last)/1000));s.last=n;const py=s.y;s.vy+=900*dt;s.y+=s.vy*dt;if(s.vy>0)for(const p of s.ps){if(py+12<=p.y&&s.y+12>=p.y){if(Math.abs(gx(p))<p.g){if(!p.p){p.p=true;s.score++;q('helixScore').textContent=`${s.score}층`}continue}if(Math.abs(hx(p))<.18){s.y=p.y-12;draw();return finish('위험 구역 착지')}s.y=p.y-12;s.vy=-360;break}}if(s.y>260){const d=s.y-260;s.y=260;s.ps.forEach(p=>p.y-=d)}s.ps=s.ps.filter(p=>p.y>-80);while(s.ps.length<10){const bot=Math.max(...s.ps.map(p=>p.y),200);s.ps.push(platform(bot+62,s.next++))}draw();raf=requestAnimationFrame(loop)}
function start(){reset();s.run=true;s.last=performance.now();s.vy=40;q('helixStatus').textContent='진행 중';q('helixStart').textContent='다시 시작';raf=requestAnimationFrame(loop)}
function stop(){cancelAnimationFrame(raf);raf=0;if(s)s.run=false;drag=null}
function open(){stop();document.querySelectorAll('#view-game .miniGamePanel').forEach(e=>e.hidden=true);q('gameHub').hidden=true;q('miniGameTopbar').hidden=false;q('miniGameTitle').textContent='헬릭스 점프';q('gameHelixPanel').hidden=false;reset()}
function bind(){q('helixStart').onclick=start;q('helixLeft').onclick=()=>rotate(-.36);q('helixRight').onclick=()=>rotate(.36);const c=q('helixCanvas');c.onpointerdown=e=>{drag={x:e.clientX,id:e.pointerId};try{c.setPointerCapture(e.pointerId)}catch(_){}};c.onpointermove=e=>{if(!drag||drag.id!==e.pointerId)return;const d=e.clientX-drag.x;drag.x=e.clientX;rotate(d*.018)};c.onpointerup=c.onpointercancel=e=>{if(drag?.id===e.pointerId)drag=null};window.addEventListener('keydown',e=>{if(q('gameHelixPanel')&&!q('gameHelixPanel').hidden&&(e.key==='ArrowLeft'||e.key==='ArrowRight')){e.preventDefault();rotate(e.key==='ArrowLeft'?-.28:.28)}})}
function wrap(){baseOpen=window.openMiniGame;baseHub=window.showMiniGameHub;baseStop=window.stopActiveMiniGame;if(typeof baseOpen!=='function')return false;window.openMiniGame=function(g){if(g===G)return open();stop();return baseOpen.apply(this,arguments)};if(typeof baseHub==='function')window.showMiniGameHub=function(){stop();const r=baseHub.apply(this,arguments);q('gameHelixPanel').hidden=true;return r};if(typeof baseStop==='function')window.stopActiveMiniGame=function(){stop();return baseStop.apply(this,arguments)};return true}
function install(){if(installed)return;if(typeof window.openMiniGame!=='function'||!document.querySelector('#gameHub .gameCardGrid'))return setTimeout(install,120);installed=true;style();card();panel();bind();wrap();reset()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',install,{once:true}):install();})();
